name: Open Sprints
version: 1
release: brifter
icons:
#  win32: platform/msw/App.ico
#  osx:   platform/mac/App.icns
  gtk:   media/logo.png
dmg:
  ds_store: platform/mac/dmg_ds_store
  background: static/hacketyhack-dmg.jpg
run: app/new.rb
clone: git checkout-index --prefix=dist/app/ -a
ignore: [firmware, hardware]
