# == Choose a Sensor
# Which sensor type you will be using?
# basic_message_arduino - the main sensor type for racing
# advanced_message_arduino - for debugging without hall effect boards
# mock - for debugging without a sensor
sensor:
  type: basic_message_arduino
# Device is where the UBW is located in your system, usually:
#   Mac OS X: /dev/tty.usbmodem0000103D1
#   Linux: /dev/ttyUSB0
#   Windows: com6
  device: /dev/ttyUSB0

# == Choose a Track
# What display would you like?
#   progress_bars - the classic race window
#   circle_track - the *actual* classic race window (experimental)
track: progress_bars

# how long the race should be, in meters
race_distance: 200

# the size of each roller, in meters
roller_circumference: 1.0

#the title displayed
title: Open Sprints

#the measurement system displayed: standard or metric
units: standard
#units: metric


# The list of racers' colors. Supports from 1-4 racers.
# Provide as many colors as you want racers.
# Can be in any format shoes understands:
# e.g.: "red" or '"#FF0000"' or "rgb(255,0,0)"
bikes:
- red
- blue

#the background image.
background_image:
menu_background_image: media/background.png
#the background color.
background_color: "\"#bec0c2\"...\"#86888b\""

# Sets the height and width of the race window. Blank to auto-detect.
window_height:
window_width:

# Sets the ammount of the screen that is usable
# (IE the lowest buttons can be placed to be usable)

# The language you want to use, e.g. 'it' for Italian, 'es' for Spanish.
locale: 'en'
